### ISSUE TITLE
Issue with connecting V slides from simai to Ma2 1.04

### ISSUE THREAD

**Issue by MBmasher** [Neskol/MaiLib#31]
I am getting this error when trying to parse this slide from simai to Ma2_104 using CompileSimai: `1V75V71[4:2]*V35V31[4:2]`

```
Start Key:6
Expected inflection point: SLL for 4 and SLR for 0
Actual: 6
Program cannot proceed because of following error returned:
MaiLib.ParsingException
Simai Parser encountered an error while parsing after bar 21 tick 0 when parsing token V75V71[4:2] in each group "{4}, 1_, V75V71[4:2], V35V31[4:2]":
THE INFLECTION POINT GIVEN IS NOT MATCHING!
Original Stack:
   at MaiLib.SimaiParser.SlideOfToken(String token, Int32 bar, Int32 tick, Note slideStart, Double bpm) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\MaiLib\Parser\Simaiparser.cs:line 437
   at MaiLib.SimaiParser.SlideGroupOfToken(List`1 extractedTokens, Int32 bar, Int32 tick, Note startNote, Double bpm) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\MaiLib\Parser\Simaiparser.cs:line 278
   at MaiLib.SimaiParser.NoteOfToken(String token, Int32 bar, Int32 tick, Double bpm) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\MaiLib\Parser\Simaiparser.cs:line 126
   at MaiLib.SimaiParser.ChartOfToken(String[] tokens) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\MaiLib\Parser\Simaiparser.cs:line 52

   at MaiLib.SimaiParser.ChartOfToken(String[] tokens) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\MaiLib\Parser\Simaiparser.cs:line 95
   at MaichartConverter.CompileSimai.Run(String[] remainingArguments) in C:\Users\Neskol\source\repos\Neskol\MaichartConverter\Commands\CompileSimai.cs:line 76
```

**Comment by Neskol** [comment]
SLL/SLR parsing issue is fixed. Please test with the lastest `MaiLib` commit or send me the complete `simai` file so I can test on my side

**Comment by MBmasher** [comment]
Hi, this issue is fixed (seemingly) however I am now getting a different error on the same chart. I'll make a new issue with the chart file uploaded
