### ISSUE TITLE
Issue with break slides converting simai to ma2 1.04

### ISSUE THREAD

**Issue by MBmasher** [Neskol/MaiLib#33]
Chart file: https://drive.google.com/drive/folders/1milyC1Xpf1QEPGvl1W8j7UI-63wL6_Mh?usp=sharing

Error:
```
Executing CompileSimai (Compile assigned simai chart to assigned format):
    Destination : out
    Difficulty : 5
    FileLocation : C:/Users/mbmas/Desktop/customs/Catch The Glory - D-D-Dice vs. siromaru\maidata.txt
    Rotate : null
    ShiftTick : null
    TargetFormat : Ma2_104

Program cannot proceed because of following error returned:
MaiLib.ParsingException
Simai Parser encountered an error while parsing after bar 84 tick 0 when parsing token <4-7-1-4[4:10]b in each group "5_, <4-7-1-4[4:10]b, 4_, -1-7-4>5[4:10]":
The input string '10b' was not in a correct format.
Original Stack:
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at MaiLib.SimaiParser.ExtractConnectingSlides(String token) in C:\Users\mbmas\Desktop\maichartconverter\MaiLib\Parser\Simaiparser.cs:line 834
   at MaiLib.SimaiParser.NoteOfToken(String token, Int32 bar, Int32 tick, Double bpm) in C:\Users\mbmas\Desktop\maichartconverter\MaiLib\Parser\Simaiparser.cs:line 124
   at MaiLib.SimaiParser.ChartOfToken(String[] tokens) in C:\Users\mbmas\Desktop\maichartconverter\MaiLib\Parser\Simaiparser.cs:line 52

   at MaiLib.SimaiParser.ChartOfToken(String[] tokens) in C:\Users\mbmas\Desktop\maichartconverter\MaiLib\Parser\Simaiparser.cs:line 95
   at MaichartConverter.CompileSimai.Run(String[] remainingArguments) in C:\Users\mbmas\Desktop\maichartconverter\Commands\CompileSimai.cs:line 84
```

**Comment by Neskol** [comment]
Confirmed - this version of parser does not correctly recognize break connecting slide. In `Ma2_104` connecting slides have same property with parent slide and `b` after measure definitions represents a break connecting slide group. Will be fixed in recent updates
